(keyword) @keyword
(string) @string
(number) @number
(punctuation) @punctuation 
(operator) @operator
(variable) @type
(constant) @constant
(function) @function
(bool) @type
(nothing) @type
(comment) @comment
(record) @type
(function) @function
(property) @property
