	(keyword) @keyword
	(string) @string
	(number) @number
	(punctuation) @punctuation
	(operator) @operator
	(variable) @type
	(constant) @constant.builtin
	(function) @function
	(bool) @boolean
	(nothing) @type
	(comment) @comment
	(record) @type
	(function) @function
	(property) @field
	(identifier) @constant @text.emphasis (#set! "priority" 120)
	(casting) @conceal
	(duration) @number
	(type) @type
	(delimiter) @punctuation.delimiter
